version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: cmd.exe
      environment:
        PYTHON: C:\tools\miniconda3\envs\py39\python.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Create Python 3.9 env"
          command: conda create -n py39 python=3.9
      - run:
          name: "Build Dependencies"
          working_directory: ./libs/dotnet-dev 
          command: bld.bat
#      - store_artifacts:
#          path: ./libs/dotnet-dev/boost_1_77_0/stage/lib
#          destination: boost_lib
      - run:
          name: "Build Python module"
          command: python ./setup.py build
      - run:
          name: "Build Package"
          command: python ./setup.py bdist_wheel
      - store_artifacts:
          path: ./dist
          destination: dist
