version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    parameters:
      python-version:
        type: string
    #environment:
    #  PYTHON: "C:\\tools\\miniconda3\\envs\\pydotnet\\python.exe"
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - checkout
      - run: systeminfo
      - run: choco install python --version=<< parameters.python-version >> --force -y  /norestart
      - run:
          name: Installed Python version verification
          shell: bash
          command: |
            py -3.9 -m venv venv39
            source ./venv39/Scripts/activate
            python --version
      - run:
          name: "Build Dependencies"
          working_directory: ./libs/dotnet-dev 
          command: |
            $env:Path = 'C:\Users\circleci\.pyenv\pyenv-win\bin;C:\Users\circleci\.pyenv\pyenv-win\shims;' + $env:Path
            bld.bat
      - run:
          name: "Build Wheel"
          command: |
            $env:Path = 'C:\Users\circleci\.pyenv\pyenv-win\bin;C:\Users\circleci\.pyenv\pyenv-win\shims;' + $env:Path
            build_wheel.bat
      - store_artifacts:
          path: ./dist
          destination: dist

workflows:
# Commented out other version to reduce usage off CircleCI
#  build_py27:
#    jobs:
#      - build:
#          python-version: "2.7"
#  build_py35:
#    jobs:
#      - build:
#          python-version: "3.5"
#  build_py36:
#    jobs:
#      - build:
#          python-version: "3.6"
#  build_py37:
#    jobs:
#      - build:
#          python-version: "3.7"
#  build_py38:
#    jobs:
#      - build:
#          python-version: "3.8"
  build_py39:
    jobs:
      - build:
          python-version: "3.9.17"