version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  build:
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - checkout
      - run: systeminfo
      - run: choco install python --version=3.12.2 --force -y
      - run:
          name: Check Python Version
          command: |
            python --version
            pip install wheel
      - run:
          name: Build Dependencies
          command: |
            cd .\libs\dotnet-dev && .\bld.bat
      - run:
          name: Build Wheel
          command: |
            .\build_wheel.bat
      - store_artifacts:
          path: ./dist
          destination: dist

workflows:
  build_default:
    jobs:
      - build