version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    parameters:
      python-version:
        type: string
      python-env:
        type: string
    environment:
      PYTHON: C:\tools\miniconda3\envs\<< parameters.python-env >>\python.exe
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Install Python << parameters.python-version >>"
          command: conda create -n << parameters.python-env >> python=<< parameters.python-version >>
      - run:
          name: "Build Dependencies"
          working_directory: ./libs/dotnet-dev 
          command: bld.bat
      - run:
          name: "Build Wheel"
          command: build_wheel.bat
      - store_artifacts:
          path: ./dist
          destination: dist

workflows:
  build_py39:
    jobs:
      - build:
          python-version: "3.9"
          python-env: py39 
