version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    parameters:
      python-version:
        type: string
    #environment:
    #  PYTHON: "C:\\tools\\miniconda3\\envs\\pydotnet\\python.exe"
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: Install and set Python << parameters.python-version >>
          shell: powershell.exe
          command: |
            choco install pyenv-win --force
            refreshenv
            pyenv install << parameters.python-version >>
            pyenv global << parameters.python-version >>
            $env:Path = 'C:\Users\circleci\.pyenv\pyenv-win\bin;C:\Users\circleci\.pyenv\pyenv-win\shims;' + $env:Path
            python --version
      - run:
          name: "Build Dependencies"
          working_directory: ./libs/dotnet-dev 
          command: bld.bat
      - run:
          name: "Build Wheel"
          command: build_wheel.bat
      - store_artifacts:
          path: ./dist
          destination: dist

workflows:
# Commented out other version to reduce usage off CircleCI
#  build_py27:
#    jobs:
#      - build:
#          python-version: "2.7"
#  build_py35:
#    jobs:
#      - build:
#          python-version: "3.5"
#  build_py36:
#    jobs:
#      - build:
#          python-version: "3.6"
#  build_py37:
#    jobs:
#      - build:
#          python-version: "3.7"
#  build_py38:
#    jobs:
#      - build:
#          python-version: "3.8"
  build_py39:
    jobs:
      - build:
          python-version: "3.9"