version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - checkout
#      - run: systeminfo
      - run:
          name: "Build Dependencies"
          command: |
            cd libs\dotnet-dev
            dir
            bld.bat
#      - run:
#          name: "Build Python module"
#          shell: cmd.exe
#          command: |
#            python ./setup.py build
