version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Create Python 3.9 env"
          command: conda create -n py39 python=3.9
      - run:
          name: "Build Dependencies"
          working_directory: ./libs/dotnet-dev 
          environment:
            PYTHON: C:\tools\miniconda3\envs\py39\python.exe
          command: bld.bat
      - run:
          name: "Build Python module"
          environment:
            PYTHON: C:\tools\miniconda3\envs\py39\python.exe
          command: $PYTHON ./setup.py build
      - run:
          name: "Build Package"
          environment:
            PYTHON: C:\tools\miniconda3\envs\py39\python.exe
          command: $PYTHON ./setup.py bdist_wheel
      - store_artifacts:
          path: ./dist
          destination: dist
