version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  install_py39:
    steps:
      - run:
          name: "Install Python 3.9"
          command: conda create -n py39 python=3.9
  build_wheel:
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Build Dependencies"
          working_directory: ./libs/dotnet-dev 
          command: bld.bat
      - run:
          name: "Build PyDotnet Wheel"
          command: build_wheel.bat
      - store_artifacts:
          path: ./dist
          destination: dist

workflows:
  build_py39:
    jobs:
      - build_wheel
        requires:
          - install_py39
        environment:
          PYTHON: C:\tools\miniconda3\envs\py39\python.exe
